# For Loop Gauntlet

The goal of this assignment is to make you a master of utilizing for loops.
Complete all the for loop challenges on the paper. please read each challenge
carefully and make sure that your for loops display exactly what is asked. If
you finish them all, try the bonus challenge.

## Single for-loops

Write a for loop to do each the following

Display all numbers from 0 to 100

In [1]:
# Display all numbers from 0 to 100 
for i in range(0,101):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

Display all numbers from 100 to 0

In [ ]:
# Display all numbers from 100 to 0
# lr = list(range(0, 101))
# print(lr[-1:])

[100]

Display all even numbers from 2 to 100

In [20]:
# Display all even numbers from 2 to 100  
for i in range(2,101, 2):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

Display all odd numbers from 1 to 99

In [22]:
# Display all odd numbers from 1 to 99  
for i in range(1, 100, 2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

Display all numbers from 1 to 40. if the number is odd, print "odd" next to the number. if the number is even, print "even" next to the number.  
eg:  
 1 is odd  
 2 is even  
 3 is odd  
 4 is even  
 5 is odd...etc.

In [ ]:
# Display all numbers from 1 to 500.
for i in range(1,501):
    if i % 2 == 0:
        print ('is even')
    else:
        print ('is odd')

1
is odd
2
is even
3
is odd
4
is even
5
is odd
6
is even
7
is odd
8
is even
9
is odd
10
is even
11
is odd
12
is even
13
is odd
14
is even
15
is odd
16
is even
17
is odd
18
is even
19
is odd
20
is even
21
is odd
22
is even
23
is odd
24
is even
25
is odd
26
is even
27
is odd
28
is even
29
is odd
30
is even
31
is odd
32
is even
33
is odd
34
is even
35
is odd
36
is even
37
is odd
38
is even
39
is odd
40
is even
41
is odd
42
is even
43
is odd
44
is even
45
is odd
46
is even
47
is odd
48
is even
49
is odd
50
is even
51
is odd
52
is even
53
is odd
54
is even
55
is odd
56
is even
57
is odd
58
is even
59
is odd
60
is even
61
is odd
62
is even
63
is odd
64
is even
65
is odd
66
is even
67
is odd
68
is even
69
is odd
70
is even
71
is odd
72
is even
73
is odd
74
is even
75
is odd
76
is even
77
is odd
78
is even
79
is odd
80
is even
81
is odd
82
is even
83
is odd
84
is even
85
is odd
86
is even
87
is odd
88
is even
89
is odd
90
is even
91
is odd
92
is even
93
is odd
94
is even
95
is odd
96
is even
97
is odd
98
is even
99
is odd
100
is even
101
is odd
102
is even
103
is odd
104
is even
105
is odd
106
is even
107
is odd
108
is even
109
is odd
110
is even
111
is odd
112
is even
113
is odd
114
is even
115
is odd
116
is even
117
is odd
118
is even
119
is odd
120
is even
121
is odd
122
is even
123
is odd
124
is even
125
is odd
126
is even
127
is odd
128
is even
129
is odd
130
is even
131
is odd
132
is even
133
is odd
134
is even
135
is odd
136
is even
137
is odd
138
is even
139
is odd
140
is even
141
is odd
142
is even
143
is odd
144
is even
145
is odd
146
is even
147
is odd
148
is even
149
is odd
150
is even
151
is odd
152
is even
153
is odd
154
is even
155
is odd
156
is even
157
is odd
158
is even
159
is odd
160
is even
161
is odd
162
is even
163
is odd
164
is even
165
is odd
166
is even
167
is odd
168
is even
169
is odd
170
is even
171
is odd
172
is even
173
is odd
174
is even
175
is odd
176
is even
177
is odd
178
is even
179
is odd
180
is even
181
is odd
182
is even
183
is odd
184
is even
185
is odd
186
is even
187
is odd
188
is even
189
is odd
190
is even
191
is odd
192
is even
193
is odd
194
is even
195
is odd
196
is even
197
is odd
198
is even
199
is odd
200
is even
201
is odd
202
is even
203
is odd
204
is even
205
is odd
206
is even
207
is odd
208
is even
209
is odd
210
is even
211
is odd
212
is even
213
is odd
214
is even
215
is odd
216
is even
217
is odd
218
is even
219
is odd
220
is even
221
is odd
222
is even
223
is odd
224
is even
225
is odd
226
is even
227
is odd
228
is even
229
is odd
230
is even
231
is odd
232
is even
233
is odd
234
is even
235
is odd
236
is even
237
is odd
238
is even
239
is odd
240
is even
241
is odd
242
is even
243
is odd
244
is even
245
is odd
246
is even
247
is odd
248
is even
249
is odd
250
is even
251
is odd
252
is even
253
is odd
254
is even
255
is odd
256
is even
257
is odd
258
is even
259
is odd
260
is even
261
is odd
262
is even
263
is odd
264
is even
265
is odd
266
is even
267
is odd
268
is even
269
is odd
270
is even
271
is odd
272
is even
273
is odd
274
is even
275
is odd
276
is even
277
is odd
278
is even
279
is odd
280
is even
281
is odd
282
is even
283
is odd
284
is even
285
is odd
286
is even
287
is odd
288
is even
289
is odd
290
is even
291
is odd
292
is even
293
is odd
294
is even
295
is odd
296
is even
297
is odd
298
is even
299
is odd
300
is even
301
is odd
302
is even
303
is odd
304
is even
305
is odd
306
is even
307
is odd
308
is even
309
is odd
310
is even
311
is odd
312
is even
313
is odd
314
is even
315
is odd
316
is even
317
is odd
318
is even
319
is odd
320
is even
321
is odd
322
is even
323
is odd
324
is even
325
is odd
326
is even
327
is odd
328
is even
329
is odd
330
is even
331
is odd
332
is even
333
is odd
334
is even
335
is odd
336
is even
337
is odd
338
is even
339
is odd
340
is even
341
is odd
342
is even
343
is odd
344
is even
345
is odd
346
is even
347
is odd
348
is even
349
is odd
350
is even
351
is odd
352
is even
353
is odd
354
is even
355
is odd
356
is even
357
is odd
358
is even
359
is odd
360
is even
361
is odd
362
is even
363
is odd
364
is even
365
is odd
366
is even
367
is odd
368
is even
369
is odd
370
is even
371
is odd
372
is even
373
is odd
374
is even
375
is odd
376
is even
377
is odd
378
is even
379
is odd
380
is even
381
is odd
382
is even
383
is odd
384
is even
385
is odd
386
is even
387
is odd
388
is even
389
is odd
390
is even
391
is odd
392
is even
393
is odd
394
is even
395
is odd
396
is even
397
is odd
398
is even
399
is odd
400
is even
401
is odd
402
is even
403
is odd
404
is even
405
is odd
406
is even
407
is odd
408
is even
409
is odd
410
is even
411
is odd
412
is even
413
is odd
414
is even
415
is odd
416
is even
417
is odd
418
is even
419
is odd
420
is even
421
is odd
422
is even
423
is odd
424
is even
425
is odd
426
is even
427
is odd
428
is even
429
is odd
430
is even
431
is odd
432
is even
433
is odd
434
is even
435
is odd
436
is even
437
is odd
438
is even
439
is odd
440
is even
441
is odd
442
is even
443
is odd
444
is even
445
is odd
446
is even
447
is odd
448
is even
449
is odd
450
is even
451
is odd
452
is even
453
is odd
454
is even
455
is odd
456
is even
457
is odd
458
is even
459
is odd
460
is even
461
is odd
462
is even
463
is odd
464
is even
465
is odd
466
is even
467
is odd
468
is even
469
is odd
470
is even
471
is odd
472
is even
473
is odd
474
is even
475
is odd
476
is even
477
is odd
478
is even
479
is odd
480
is even
481
is odd
482
is even
483
is odd
484
is even
485
is odd
486
is even
487
is odd
488
is even
489
is odd
490
is even
491
is odd
492
is even
493
is odd
494
is even
495
is odd
496
is even
497
is odd
498
is even
499
is odd
500
is even

Display all multiples of 7 from 0 to 70

In [6]:
# Display all multiples of 7 from 0 to 777
for i in range(0,784, 7):
    print (i)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98
105
112
119
126
133
140
147
154
161
168
175
182
189
196
203
210
217
224
231
238
245
252
259
266
273
280
287
294
301
308
315
322
329
336
343
350
357
364
371
378
385
392
399
406
413
420
427
434
441
448
455
462
469
476
483
490
497
504
511
518
525
532
539
546
553
560
567
574
581
588
595
602
609
616
623
630
637
644
651
658
665
672
679
686
693
700
707
714
721
728
735
742
749
756
763
770
777

Print all the years you were alive and how old you were in each. e.g. "in 1979, i was 2 years old." (for a really old person)

In [ ]:
# Your Code Here
for y in range(2009, 2025):
    for a in range(1, 16):
        print('i was', a, 'years old in', y)

i was 1 years old in 2009
i was 2 years old in 2009
i was 3 years old in 2009
i was 4 years old in 2009
i was 5 years old in 2009
i was 6 years old in 2009
i was 7 years old in 2009
i was 8 years old in 2009
i was 9 years old in 2009
i was 10 years old in 2009
i was 11 years old in 2009
i was 12 years old in 2009
i was 13 years old in 2009
i was 14 years old in 2009
i was 15 years old in 2009
i was 1 years old in 2010
i was 2 years old in 2010
i was 3 years old in 2010
i was 4 years old in 2010
i was 5 years old in 2010
i was 6 years old in 2010
i was 7 years old in 2010
i was 8 years old in 2010
i was 9 years old in 2010
i was 10 years old in 2010
i was 11 years old in 2010
i was 12 years old in 2010
i was 13 years old in 2010
i was 14 years old in 2010
i was 15 years old in 2010
i was 1 years old in 2011
i was 2 years old in 2011
i was 3 years old in 2011
i was 4 years old in 2011
i was 5 years old in 2011
i was 6 years old in 2011
i was 7 years old in 2011
i was 8 years old in 2011
i was 9 years old in 2011
i was 10 years old in 2011
i was 11 years old in 2011
i was 12 years old in 2011
i was 13 years old in 2011
i was 14 years old in 2011
i was 15 years old in 2011
i was 1 years old in 2012
i was 2 years old in 2012
i was 3 years old in 2012
i was 4 years old in 2012
i was 5 years old in 2012
i was 6 years old in 2012
i was 7 years old in 2012
i was 8 years old in 2012
i was 9 years old in 2012
i was 10 years old in 2012
i was 11 years old in 2012
i was 12 years old in 2012
i was 13 years old in 2012
i was 14 years old in 2012
i was 15 years old in 2012
i was 1 years old in 2013
i was 2 years old in 2013
i was 3 years old in 2013
i was 4 years old in 2013
i was 5 years old in 2013
i was 6 years old in 2013
i was 7 years old in 2013
i was 8 years old in 2013
i was 9 years old in 2013
i was 10 years old in 2013
i was 11 years old in 2013
i was 12 years old in 2013
i was 13 years old in 2013
i was 14 years old in 2013
i was 15 years old in 2013
i was 1 years old in 2014
i was 2 years old in 2014
i was 3 years old in 2014
i was 4 years old in 2014
i was 5 years old in 2014
i was 6 years old in 2014
i was 7 years old in 2014
i was 8 years old in 2014
i was 9 years old in 2014
i was 10 years old in 2014
i was 11 years old in 2014
i was 12 years old in 2014
i was 13 years old in 2014
i was 14 years old in 2014
i was 15 years old in 2014
i was 1 years old in 2015
i was 2 years old in 2015
i was 3 years old in 2015
i was 4 years old in 2015
i was 5 years old in 2015
i was 6 years old in 2015
i was 7 years old in 2015
i was 8 years old in 2015
i was 9 years old in 2015
i was 10 years old in 2015
i was 11 years old in 2015
i was 12 years old in 2015
i was 13 years old in 2015
i was 14 years old in 2015
i was 15 years old in 2015
i was 1 years old in 2016
i was 2 years old in 2016
i was 3 years old in 2016
i was 4 years old in 2016
i was 5 years old in 2016
i was 6 years old in 2016
i was 7 years old in 2016
i was 8 years old in 2016
i was 9 years old in 2016
i was 10 years old in 2016
i was 11 years old in 2016
i was 12 years old in 2016
i was 13 years old in 2016
i was 14 years old in 2016
i was 15 years old in 2016
i was 1 years old in 2017
i was 2 years old in 2017
i was 3 years old in 2017
i was 4 years old in 2017
i was 5 years old in 2017
i was 6 years old in 2017
i was 7 years old in 2017
i was 8 years old in 2017
i was 9 years old in 2017
i was 10 years old in 2017
i was 11 years old in 2017
i was 12 years old in 2017
i was 13 years old in 2017
i was 14 years old in 2017
i was 15 years old in 2017
i was 1 years old in 2018
i was 2 years old in 2018
i was 3 years old in 2018
i was 4 years old in 2018
i was 5 years old in 2018
i was 6 years old in 2018
i was 7 years old in 2018
i was 8 years old in 2018
i was 9 years old in 2018
i was 10 years old in 2018
i was 11 years old in 2018
i was 12 years old in 2018
i was 13 years old in 2018
i was 14 years old in 2018
i was 15 years old in 2018
i was 1 years old in 2019
i was 2 years old in 2019
i was 3 years old in 2019
i was 4 years old in 2019
i was 5 years old in 2019
i was 6 years old in 2019
i was 7 years old in 2019
i was 8 years old in 2019
i was 9 years old in 2019
i was 10 years old in 2019
i was 11 years old in 2019
i was 12 years old in 2019
i was 13 years old in 2019
i was 14 years old in 2019
i was 15 years old in 2019
i was 1 years old in 2020
i was 2 years old in 2020
i was 3 years old in 2020
i was 4 years old in 2020
i was 5 years old in 2020
i was 6 years old in 2020
i was 7 years old in 2020
i was 8 years old in 2020
i was 9 years old in 2020
i was 10 years old in 2020
i was 11 years old in 2020
i was 12 years old in 2020
i was 13 years old in 2020
i was 14 years old in 2020
i was 15 years old in 2020
i was 1 years old in 2021
i was 2 years old in 2021
i was 3 years old in 2021
i was 4 years old in 2021
i was 5 years old in 2021
i was 6 years old in 2021
i was 7 years old in 2021
i was 8 years old in 2021
i was 9 years old in 2021
i was 10 years old in 2021
i was 11 years old in 2021
i was 12 years old in 2021
i was 13 years old in 2021
i was 14 years old in 2021
i was 15 years old in 2021
i was 1 years old in 2022
i was 2 years old in 2022
i was 3 years old in 2022
i was 4 years old in 2022
i was 5 years old in 2022
i was 6 years old in 2022
i was 7 years old in 2022
i was 8 years old in 2022
i was 9 years old in 2022
i was 10 years old in 2022
i was 11 years old in 2022
i was 12 years old in 2022
i was 13 years old in 2022
i was 14 years old in 2022
i was 15 years old in 2022
i was 1 years old in 2023
i was 2 years old in 2023
i was 3 years old in 2023
i was 4 years old in 2023
i was 5 years old in 2023
i was 6 years old in 2023
i was 7 years old in 2023
i was 8 years old in 2023
i was 9 years old in 2023
i was 10 years old in 2023
i was 11 years old in 2023
i was 12 years old in 2023
i was 13 years old in 2023
i was 14 years old in 2023
i was 15 years old in 2023
i was 1 years old in 2024
i was 2 years old in 2024
i was 3 years old in 2024
i was 4 years old in 2024
i was 5 years old in 2024
i was 6 years old in 2024
i was 7 years old in 2024
i was 8 years old in 2024
i was 9 years old in 2024
i was 10 years old in 2024
i was 11 years old in 2024
i was 12 years old in 2024
i was 13 years old in 2024
i was 14 years old in 2024
i was 15 years old in 2024

## Nested for-loops

Write nested for loops (a for loop inside another for loop). Here is an example of nested loops.

In [18]:
# Examples of Nested Loops

for i in range(8):
    for j in range(8):
        print(f"({i},{j})", end= ' ')
    print()

(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7)
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) (5,6) (5,7)
(6,0) (6,1) (6,2) (6,3) (6,4) (6,5) (6,6) (6,7)
(7,0) (7,1) (7,2) (7,3) (7,4) (7,5) (7,6) (7,7)

For your first nested loop, display this output:  

```
0  0  
0  1  
0  2  
1  0  
1  1  
1  2  
2  0  
2  1  
2  2
```

In [21]:
# Display the output shown above
for i in range(3):
    for t in range(3):
        print(f"{i} {t}")

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2

Display the numbers 1 through 9 in a 3x3 square grid like this:  

```
1  2  3  
4  5  6  
7  8  9  
```

In [70]:
# Display the numbers 1 through 9 in a 3x3 square grid
for i in range(3):
    for j in range(3):
        print(f"{j+i*3+1}", end= ' ')
    print('')

1 2 3
4 5 6
7 8 9

Display the numbers 1 through 100 in a 10x10 square grid.

In [72]:
# Display the numbers 1 through 100 in a 10x10 square grid. 
for i in range(10):
    for j in range(10):
        print(f"{j+i*10+1}", end= ' ')
    print('')

1 2 3 4 5 6 7 8 9 10
11 12 13 14 15 16 17 18 19 20
21 22 23 24 25 26 27 28 29 30
31 32 33 34 35 36 37 38 39 40
41 42 43 44 45 46 47 48 49 50
51 52 53 54 55 56 57 58 59 60
61 62 63 64 65 66 67 68 69 70
71 72 73 74 75 76 77 78 79 80
81 82 83 84 85 86 87 88 89 90
91 92 93 94 95 96 97 98 99 100

Display the following output:  

```
*  
*  *  
*  *  *  
*  *  *  *  
*  *  *  *  *  
*  *  *  *  *  *
```

In [84]:
# Display the asterisk pattern shown above
for i in range(7):
    for j in range(i):
        print(f"{'*'}", end= ' ')
    print('')

*
* *
* * *
* * * *
* * * * *
* * * * * *